#pragma once

#include <iostream>
#include <vector>
#include <algorithm>
#include <functional>
#include <ctime>
#include <cstdlib>
#include <iomanip>
#include <array>
#include <memory>
#include <thread>
#include <utility>
#include <string>
#include <stack>
#include <map>
#include <unordered_map>
#include <set>
#include <unordered_set>
#include <chrono>
#include <regex>
#include <fstream>
#include <queue>